create database ScottyTest CHARACTER SET utf8 COLLATE utf8_bin;
use ScottyTest;
create table Items (id int not null auto_increment, name varchar(300), price decimal (10, 2), count decimal (10, 2), primary key (id));
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);
insert into Items (name, count, price) values ('Cheese', 100, 290);